### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by tanhanjay** [math2001/MarkdownLivePreview#17]
- This plugin seems not has code highlight function 
![image](https://cloud.githubusercontent.com/assets/13805551/22537403/46404130-e945-11e6-9ef1-e00cb17a7fcc.png)
- And if I open md file include hexo's frontmatter this plugin may has been in trouble and will not work! Please fix it !
![image](https://cloud.githubusercontent.com/assets/13805551/22537507/1720ca40-e946-11e6-8799-b48cfe2c5607.png)

**Comment by math2001** [comment]
> This plugin seems not has code highlight function

This code is highlighted with pygments (which, for it to work for everyone, would have to be a dependency). So, this means that I'd have to manually set specific classes to have certain fg/bg/style, depending on the color scheme. Unless you have a really quick solution, I have, for now, not plan on adding this. (I'd gladly accept PR, though)

> And if I open md file include hexo's frontmatter this plugin may has been in trouble and will not work!

I'll have a look for this

**Comment by math2001** [comment]
Ok, I find the reason why: Phantom do not support `<hr/>`, but `<hr />` (same for `br`). And because `----` is, in markdown, replaced by a `<hr>` and that BeautifulSoup replaces it with `<hr/>`, it made everything go wrong. 

So, this is fixed, but I suppose that you want to remove this header? Or show it in a pre? Or even add an option to choose? **What'd you expect?**

**Comment by tanhanjay** [comment]
Thank you very much! After your last commit, I'd try it and now it's really great!

**Comment by math2001** [comment]
Cool! Just by curiosity: do you remove the front matter, or leave it in a `<pre>`?
