### ISSUE TITLE
Image size should adopt to window width

### ISSUE THREAD

**Issue by binaryanomaly** [math2001/MarkdownLivePreview#48]
Images unfortunately seem to be displayed in original size and not scaled down to a size that would fit the window. I seem not be able to change this with css since the img property is not supported.
Would be nice if images would dynamically scale to fit the window width.

This is the only thing that is really bothering me apart from this the plugin is very helpful 👍🏻

**Comment by math2001** [comment]
This actually looks easier because `img` tags seem to support `width` and `height` *attributes* (although it's not documented on the minihtml page). We can get the size of the image using something [like that](https://stackoverflow.com/questions/8032642/how-to-obtain-image-size-using-standard-python-class-without-using-external-lib). And then, we have to determine the width the preview using something like `viewport_extent()` or `layout_extent()`
