### ISSUE TITLE
use with other syntaxes other than .md

### ISSUE THREAD

**Issue by michapixel** [math2001/MarkdownLivePreview#88]
I used this (as a hack) for renderring .tpl files (simple html in my case) for some reason. And it works, partly. 
But i have to switch highlighting to MarkDownLive... once in the source file to make alt+m work. And secondly for the then opened file + preview. 
But i don't think this coulkd be done easyer, does it?

**Comment by math2001** [comment]
> But i don't think this coulkd be done easyer, does it?

We could manually check for the file extension, but this wouldn't be correct since this is the syntax's file/user setting's job, not ours. What makes sense is for us to check that the syntax file is markdown-like.

One thing you could do is set the default syntax for `.tpl` files to markdown (click on the bottom right, and then at the top `Open all current extension as` and then `markdown`)
