### ISSUE TITLE
Some images load, some show load icon, some doesn't

### ISSUE THREAD

**Issue by maifeeulasad** [math2001/MarkdownLivePreview#90]
I was reading codes from a project. Then for some reasons, I thought I should be reading .md file offline. Then I came to know about this - MarkdownLivePreview.

Now, when I started reading the .md file I had, I noticed something different.

**One picture is being rendered, other is not.**

But the link is fresh and live, [here](https://github.com/hanyizhao/NetSpeedMonitor/blob/master/Screenshots/2.png)

Here is a snap :

![partial render)](https://user-images.githubusercontent.com/29339330/67596246-1c120000-f78a-11e9-9543-2496628b23f7.png)

And sometimes it shows a loading like image:

![loading for more than 5 minutes](https://user-images.githubusercontent.com/29339330/67596325-4794ea80-f78a-11e9-9b9b-52eb4ebcb352.png)

**Comment by math2001** [comment]
The code fetching the images is a bit dodgy... It would need to be re-written. Basically, the image is only updated when the whole preview is updated (basically when you press a key). There is currently no callback which re-renders the preview as soon as the image has finished loading. So, if you wanna see the pictures, you have to type in things (space backspace in repeat would work).

Having a callback is technically possible though, it's just not implemented yet, mainly because the code is quite messy and I don't have a hip of free time right now (I'm passing the HSC), but that should change soon 🙂

**Comment by maifeeulasad** [comment]
@math2001  can you assign me into this issue ?

I'm interested.

**Comment by math2001** [comment]
Hey, thank you for wanting to contribute :heart:!

Here's probably where you wanna start:

https://github.com/math2001/MarkdownLivePreview/blob/master/image_manager.py#L62

Just to give you my personal opinion: this package is just a stack of bad code, disorganized and unclear. I think everything should be re-written, properly. It's still possible to add in this feature, but don't feel bad if you don't feel like it's going to be worth the effort 🙂

**Comment by maifeeulasad** [comment]
Thanks a lot for assigning me.


My opinion is - why don't we try to fix this thing,
meanwhile we re-write from scratch.

**Comment by math2001** [comment]
I've unassigned you because I have rewritten MarkdownLivePreview, and this issue is now fixed really cleanly. It turned out to be a lot easier to implement than I original thought, and I probably could now do it in the current code base. The whole package needed to be re-written anyway, just to make it easier for people to contribute.

It's only on my computer for now, but it should arrive soon :slightly_smiling_face:

**Comment by maifeeulasad** [comment]
Its awesome.

**Comment by math2001** [comment]
This is fixed by [`v3.0.0`](https://github.com/math2001/MarkdownLivePreview/releases/tag/v3.0.0) :slightly_smiling_face: 

This is how the "image manager" (just a function) is used:

https://github.com/math2001/MarkdownLivePreview/blob/192f61bf0ced21b906bfb98102e556498b9196d4/markdown2html.py#L60-L65

And this is the "image manager"

https://github.com/math2001/MarkdownLivePreview/blob/192f61bf0ced21b906bfb98102e556498b9196d4/markdown2html.py#L99-L138
